version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_sharing_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: file_sharing_db
    ports:
      - "8080:8080"  # Add this line to expose port 8080
    env_file:
      - .env  
    depends_on:
      - db
      - redis

volumes:
  pgdata:
